apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: pi
  name: pi
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: aba4ac03-f41b-11e8-a3df-0a346082443e
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: aba4ac03-f41b-11e8-a3df-0a346082443e
        job-name: pi
        run: pi
    spec:
      containers:
      - args:
        - perl
        - -Mbignum=bpi
        - -wle
        - print bpi(2000)
        image: perl
        imagePullPolicy: Always
        name: pi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  completionTime: 2018-11-29T21:14:41Z
  conditions:
  - lastProbeTime: 2018-11-29T21:14:41Z
    lastTransitionTime: 2018-11-29T21:14:41Z
    status: "True"
    type: Complete
  startTime: 2018-11-29T21:13:51Z
  succeeded: 1
