apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generateName: federationv2-
spec:
  source: rh-operators
  sourceNamespace: openshift-operator-lifecycle-manager
  name: federationv2
  startingCSV: federationv2.v0.0.2
  channel: alpha
