apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generateName: mongodb-enterprise-
  namespace: my-operators
spec:
  source: certified-operators
  sourceNamespace: openshift-operator-lifecycle-manager
  name: mongodb-enterprise
  startingCSV: mongodboperator.v0.3.2
  channel: preview
